### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by pporada-gl** [jugglingdb/mysql-adapter#106]
Is this project still alive? I see the last update was made ~3 months ago.

Additionally, what versions of MySQL does this support? Am I able to use MySQL 5.7 or am I stuck with MySQL 5.5/5.6?

**Comment by 1602** [comment]
We use 5.5 in production, but in my tests it works just fine with 5.7. Speaking of question whether this project is alive or not I would say it is not actively maintained, but still used in production. Every time I encounter bug I try to fix it.
